name: farmgate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+29

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  test: ^1.15.5
  cupertino_icons: ^1.0.0
  simplest: ^1.0.1+2
  freezed_annotation: ^0.12.0
  flutter_staggered_grid_view: ^0.3.2
  carousel_slider: ^2.3.1
  youtube_player_flutter: ^7.0.0+7
  uuid: ^2.2.0
  multi_image_picker: ^4.7.10
  local_auth: ^0.6.3+4
  flutter_html: ^1.0.2
  flutter_inappwebview: ^4.0.0+4
  path_provider: ^1.6.9
  permission_handler: ^5.0.0+hotfix.6
  provider: ^4.1.3
  share: ^0.6.5+4
  random_color: ^1.0.5
  flutter_native_image: ^0.0.5+3
  scroll_to_index: ^1.0.6
  dotted_border: ^1.0.7
  flutter_reaction_button: ^1.0.6+1
  firebase_crashlytics: ^0.4.0
  flutter_device_type: ^0.3.2
  maps_toolkit: ^1.1.0+2
  pull_to_refresh: 1.6.3
  fdottedline: ^1.0.1
  timelines: ^0.0.2+1
  flutter_typeahead: ^2.0.0
  qr_flutter: ^3.2.0
  dotted_line: ^2.0.2
  currency_text_input_formatter: ^1.0.4

dependency_overrides:
  analyzer: 0.40.6
  firebase_core: 0.5.2
  firebase_core_platform_interface: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.2
  retrofit_generator: ^1.4.0+1
  injectable_generator: ^1.0.6
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.3

# flutter pub get && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/
    - assets/svg/
